//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCompanionBookingManagementSystem.Customer
{
    public partial class RateCompanion
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.HyperLink NavDashboard;
        protected global::System.Web.UI.WebControls.HyperLink NavCompanions;
        protected global::System.Web.UI.WebControls.HyperLink NavBookings;
        protected global::System.Web.UI.WebControls.HyperLink NavNotifications;
        protected global::System.Web.UI.WebControls.HyperLink NavProfile;
        protected global::System.Web.UI.WebControls.HyperLink hlNotifBell;
        protected global::System.Web.UI.WebControls.Image imgTopAvatar;
        protected global::System.Web.UI.WebControls.Literal litAvatarInitial;
        protected global::System.Web.UI.WebControls.Literal litUserFirstName;
        protected global::System.Web.UI.WebControls.Image imgDropAvatar;
        protected global::System.Web.UI.WebControls.Literal litAvatarInitialLg;
        protected global::System.Web.UI.WebControls.Literal litDropdownName;
        protected global::System.Web.UI.WebControls.Literal litDropdownEmail;
        protected global::System.Web.UI.WebControls.HyperLink hlProfileLink;
        protected global::System.Web.UI.WebControls.HyperLink hlSettingsLink;
        protected global::System.Web.UI.WebControls.Button btnDropdownLogout;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Panel pnlRatingForm;
        protected global::System.Web.UI.WebControls.Literal litCompanionName;
        protected global::System.Web.UI.WebControls.Literal litPackageName;
        protected global::System.Web.UI.WebControls.Literal litBookingDate;
        protected global::System.Web.UI.WebControls.RadioButtonList rblScore;
        protected global::System.Web.UI.WebControls.CustomValidator cvScore;
        protected global::System.Web.UI.WebControls.TextBox txtComment;
        protected global::System.Web.UI.WebControls.HyperLink hlBack;
        protected global::System.Web.UI.WebControls.Button btnSubmitRating;
    }
}
